# This file is a template, and might need editing before it works on your project.
image: node:11.9

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

pages:
  tags:
    - node:11.9
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - public
    expire_in: 1 days
  only:
    - master
